name: Cat of the Minute

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-cat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: python scripts/update_cat.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          git diff --cached --quiet || (
            git commit -m "🐱 Update cat image"
            git push
          )